global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "monitoring"
    metrics_path: /metrics
    static_configs:
      - targets:
          - monitoring:8000

rule_files:
  - /etc/prometheus/rules.yml