groups:
- name: app-http
  rules:
  # Canonical counter: requests by instance+status (works for Django OR FastAPI)
  - record: app_http_requests_total
    expr: |
      # Django responses counter
      sum by (instance, status) (
        rate(django_http_responses_total_by_status_view_transport_method_total[1m])
      )
      OR
      # FastAPI/ASGI common counter
      sum by (instance, status) (
        rate(http_requests_total[1m])
      )

  # Canonical latency histogram buckets by instance+le
  - record: app_http_request_duration_seconds_bucket
    expr: |
      # Django latency histogram
      sum by (instance, le) (
        rate(django_http_requests_latency_seconds_by_view_transport_method_bucket[5m])
      )
      OR
      # FastAPI/ASGI latency histogram
      sum by (instance, le) (
        rate(http_request_duration_seconds_bucket[5m])
      )