# Generated by Django 5.2.7 on 2025-10-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('expected_status', models.IntegerField(default=200)),
                ('timeout_ms', models.IntegerField(default=5000)),
                ('interval_sec', models.IntegerField(default=60)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('status', models.CharField(max_length=50)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('success', models.BooleanField()),
                ('details', models.TextField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='api.endpoint')),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='api.service'),
        ),
    ]
