# Generated by Django 5.2.7 on 2025-10-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='method',
            field=models.CharField(choices=[('GET', 'get'), ('POST', 'post'), ('PUT', 'put'), ('DELETE', 'delete'), ('PATCH', 'patch'), ('HEAD', 'head'), ('OPTIONS', 'options')], default='GET', max_length=10),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('service', 'url', 'method')},
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['endpoint', '-timestamp'], name='api_checkre_endpoin_7fc2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['service', 'enabled', 'next_run_at'], name='api_endpoin_service_9307e2_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='api_service_name_a13a6e_idx'),
        ),
    ]
